[build]
  command = "node scripts/generate-env.js && ng build --configuration production"
  functions = "netlify/functions"
  publish = "dist/nullable-web"

  ## Not needed for static site generators.
  [[redirects]]
    from = "/*"
    to = "/index.html"
    status = 200
